"""Emergency/manual storefront mockup fallback.

Production storefront imagery should be generated by tools/refresh_printful_mockups.py
using Printful's native Comfort Colors 1717 mockup renderer. This deterministic
shirt drawing remains only for cases where provider-native generation is unavailable.
"""

from __future__ import annotations

import hashlib
import random
from pathlib import Path

from PIL import Image, ImageChops, ImageDraw, ImageFilter

ROOT = Path(__file__).resolve().parents[1]
PRINTS = ROOT / "black_metal_buddhist_prints"
OUT = ROOT / "app" / "static" / "products"

CANVAS = 1200
BACKGROUND = (43, 43, 43)  # Brand Ash Charcoal #2B2B2B
SHIRT_BASE = (8, 8, 8)
SHIRT_HIGHLIGHT = (20, 20, 20)
SHIRT_SHADOW = (2, 2, 2)

# Production is frozen on the Printful Comfort Colors 1717 DTG front placement.
# Printful's current guidance uses a 12 x 16 inch full-front area for most tees;
# the 15 x 18 inch large-front program applies only to selected products and does
# not currently list the 1717. The approved BMB masters are already 3600 x 4800
# px at 300 dpi (12 x 16 in), so the storefront mockup now models that exact
# canvas instead of the smaller-garment 11.5 x 13.8 in large-front fallback.
REFERENCE_PRINT_IN = (12.0, 16.0)
REFERENCE_PRINT_PX = (3600, 4800)

# Printful recommends positioning a full-front design roughly 3-4 inches below
# the collar. This box is centered on the shirt and visually calibrated to that
# placement while preserving the production 3:4 aspect ratio exactly.
PRINT_BOX = (405, 310, 795, 830)  # 390 x 520 px, exact 12:16 ratio

PRODUCTS = {
    "lotus-of-the-void": PRINTS / "03_two_ink_png" / "lotus_of_the_void_two_ink_12x16_300dpi.png",
    "dharma-of-decay": PRINTS / "03_two_ink_png" / "dharma_of_decay_two_ink_12x16_300dpi.png",
    "meditate-on-death": PRINTS / "03_two_ink_png" / "meditate_on_death_two_ink_12x16_300dpi.png",
    "longchenpa-rest-in-illusion": PRINTS / "03_two_ink_png" / "longchenpa_rest_in_illusion_two_ink_12x16_300dpi.png",
}


def _noise(size: tuple[int, int], seed: int, amplitude: int = 10) -> Image.Image:
    rnd = random.Random(seed)
    pixels = bytearray(size[0] * size[1])
    for i in range(len(pixels)):
        pixels[i] = max(0, min(255, 128 + rnd.randint(-amplitude, amplitude)))
    return Image.frombytes("L", size, bytes(pixels))


def _background() -> Image.Image:
    image = Image.new("RGB", (CANVAS, CANVAS), BACKGROUND)
    # Subtle vignette and stone/fabric texture, intentionally brand-neutral.
    vignette = Image.new("L", (CANVAS, CANVAS), 0)
    draw = ImageDraw.Draw(vignette)
    for radius in range(830, 190, -12):
        value = int(210 * (1 - (radius - 190) / 640))
        box = (CANVAS // 2 - radius, CANVAS // 2 - radius,
               CANVAS // 2 + radius, CANVAS // 2 + radius)
        draw.ellipse(box, fill=max(0, min(210, value)))
    vignette = vignette.filter(ImageFilter.GaussianBlur(70))
    glow = Image.new("RGB", image.size, (26, 26, 26))
    image = Image.composite(glow, image, vignette)

    noise = _noise(image.size, seed=1717, amplitude=13).filter(ImageFilter.GaussianBlur(.35))
    texture = Image.merge("RGB", (noise, noise, noise))
    image = Image.blend(image, texture, .075)
    return image


def _shirt_mask() -> Image.Image:
    mask = Image.new("L", (CANVAS, CANVAS), 0)
    d = ImageDraw.Draw(mask)
    # Classic black tee silhouette. Torso width/height approximates a relaxed
    # unisex blank while sleeves keep the mockup visually consistent.
    points = [
        (404, 176), (326, 218), (181, 337), (245, 467),
        (344, 410), (350, 1040), (850, 1040), (856, 410),
        (955, 467), (1019, 337), (874, 218), (796, 176),
        (706, 148), (494, 148),
    ]
    d.polygon(points, fill=255)
    # Shoulder rounding / torso fill.
    d.rounded_rectangle((342, 180, 858, 1042), radius=52, fill=255)
    return mask.filter(ImageFilter.GaussianBlur(.7))


def _shirt_layer(mask: Image.Image) -> Image.Image:
    # Soft shadow below/around shirt.
    shadow_mask = mask.filter(ImageFilter.GaussianBlur(28))
    shadow = Image.new("RGBA", (CANVAS, CANVAS), (0, 0, 0, 175))
    shadow.putalpha(shadow_mask)

    base = Image.new("RGBA", (CANVAS, CANVAS), (*SHIRT_BASE, 255))
    base.putalpha(mask)

    # Broad fabric highlight through the center of the torso.
    grad = Image.new("L", (CANVAS, CANVAS), 0)
    gp = grad.load()
    for y in range(CANVAS):
        for x in range(CANVAS):
            dx = abs(x - CANVAS / 2) / 340
            dy = abs(y - 560) / 650
            v = int(max(0, 46 * (1 - min(1, dx * .85 + dy * .18))))
            gp[x, y] = v
    highlight = Image.new("RGBA", (CANVAS, CANVAS), (*SHIRT_HIGHLIGHT, 255))
    highlight.putalpha(ImageChops.multiply(mask, grad))

    fabric = _noise((CANVAS, CANVAS), seed=3001, amplitude=18).filter(ImageFilter.GaussianBlur(.4))
    fabric_rgba = Image.new("RGBA", (CANVAS, CANVAS), (255, 255, 255, 0))
    fabric_rgba.putalpha(ImageChops.multiply(mask, fabric.point(lambda p: max(0, p - 104))))

    composite = Image.new("RGBA", (CANVAS, CANVAS), (0, 0, 0, 0))
    composite.alpha_composite(shadow)
    composite.alpha_composite(base)
    composite.alpha_composite(highlight)
    composite.alpha_composite(fabric_rgba)
    return composite


def _collar_and_seams(canvas: Image.Image) -> None:
    d = ImageDraw.Draw(canvas)
    # Collar hole and ribbing.
    d.ellipse((477, 132, 723, 262), fill=(3, 3, 3, 255), outline=(33, 33, 33, 255), width=11)
    d.arc((493, 148, 707, 246), 10, 170, fill=(47, 47, 47, 255), width=3)
    # Sleeve and hem seams.
    seam = (33, 33, 33, 210)
    d.line((205, 375, 337, 447), fill=seam, width=4)
    d.line((995, 375, 863, 447), fill=seam, width=4)
    d.line((365, 1015, 835, 1015), fill=seam, width=4)


def _prepare_art(image: Image.Image) -> Image.Image:
    image = image.convert("RGBA")
    if image.size != REFERENCE_PRINT_PX:
        raise RuntimeError(
            f"print master must be {REFERENCE_PRINT_PX[0]}x{REFERENCE_PRINT_PX[1]} px; "
            f"got {image.size[0]}x{image.size[1]}"
        )
    if not image.getchannel("A").getbbox():
        raise RuntimeError("print master is fully transparent")
    return image


def _place_art(canvas: Image.Image, art: Image.Image) -> None:
    x0, y0, x1, y1 = PRINT_BOX
    box_w, box_h = x1 - x0, y1 - y0
    art = _prepare_art(art)

    # Scale the *entire* 12 x 16 transparent production canvas. This preserves
    # the intentional offsets/margins recorded in PRINT_SPECIFICATIONS.json,
    # which is closer to how the uploaded Printful print file is positioned than
    # cropping to the non-transparent artwork bounds first.
    scale = min(box_w / art.width, box_h / art.height)
    size = (max(1, round(art.width * scale)), max(1, round(art.height * scale)))
    art = art.resize(size, Image.Resampling.LANCZOS)

    # A tiny fabric interaction keeps the design from looking pasted on.
    alpha = art.getchannel("A")
    weave = _noise(size, seed=666, amplitude=5)
    alpha = ImageChops.multiply(alpha, weave.point(lambda p: min(255, 240 + (p - 128) // 3)))
    art.putalpha(alpha)

    px = x0 + (box_w - size[0]) // 2
    py = y0 + (box_h - size[1]) // 2
    canvas.alpha_composite(art, (px, py))


def build(slug: str, source: Path) -> Path:
    if not source.exists():
        raise FileNotFoundError(source)

    background = _background().convert("RGBA")
    shirt_mask = _shirt_mask()
    background.alpha_composite(_shirt_layer(shirt_mask))
    _collar_and_seams(background)
    _place_art(background, Image.open(source))

    # Final shadow under hem.
    d = ImageDraw.Draw(background)
    d.ellipse((330, 1018, 870, 1080), fill=(0, 0, 0, 42))

    OUT.mkdir(parents=True, exist_ok=True)
    path = OUT / f"{slug}.webp"
    background.convert("RGB").resize((900, 900), Image.Resampling.LANCZOS).save(
        path, "WEBP", quality=88, method=6
    )
    return path


def main() -> None:
    print(
        "Mockup reference: Printful Comfort Colors 1717 DTG front, "
        f"{REFERENCE_PRINT_IN[0]:g} x {REFERENCE_PRINT_IN[1]:g} in; "
        "full-front placement calibrated ~3-4 in below collar"
    )
    for slug, source in PRODUCTS.items():
        path = build(slug, source)
        digest = hashlib.sha256(path.read_bytes()).hexdigest()
        with Image.open(path) as check:
            check.load()
            print(slug, check.size, len(path.read_bytes()), digest)


if __name__ == "__main__":
    main()
